#!/usr/bin/env python
# coding: utf-8

# # 資料來源與檔案存取
# 
# * 資料來源與取得
# * 開放資料
# * 資料儲存格式
# * Python 存取檔案

# ## 作業目標
# ### 1.（簡答題）檔案、API、爬蟲三種取得資料方式有什麼不同？

# ### 2.（實作）完成一個程式，需滿足下列需求：
#     * 下載指定檔案到 Data 資料夾，存成檔名 Homework.txt
#     * 檢查 Data 資料夾是否有 Homework.txt 檔名之檔案
#     * 將「Hello World」字串覆寫到 Homework.txt 檔案
#     * 檢查 Homework.txt 檔案字數是否符合 Hello World 字數
# 

# In[1]:


# 根據需求引入正確的 Library

from urllib.request import urlretrieve
import os


# In[2]:


# 下載檔案到 Data 資料夾，存成檔名 Homework.txt

try:
    os.makedirs( './Data', exist_ok=True )
       
    #下載指定檔案到 Data 資料夾，存成檔名 Homework.txt
    urlretrieve("https://www.w3.org/TR/PNG/iso_8859-1.txt","./data/Homework.txt")

    
except:
    print('發生錯誤！')


# In[3]:


# 檢查 Data 資料夾是否有 Homework.txt 檔名之檔案


files = []
files = os.listdir('./data/')
'''
Your Code
'''

if 'Homework.txt' in files:
    print('[O] 檢查 Data 資料夾是否有 Homework.txt 檔名之檔案')
else:
    print('[X] 檢查 Data 資料夾是否有 Homework.txt 檔名之檔案')


# In[5]:


# 將「Hello World」字串覆寫到 Homework.txt 檔案

f = 'Hello World'

with open("./Data/Homework.txt", "w") as fh:
    fh.write(f)

try:
    with open("./Data/Homework.txt", "r") as fh:
        ff = fh.read()
except EnvironmentError: # parent of IOError, OSError *and* WindowsError where available
    pass    


# In[6]:


# 檢查 Homework.txt 檔案字數是否符合 Hello World 字數

if len('Hello World') == len(ff):
    print('[O] 檢查 Homework.txt 檔案字數是否符合 Hello World 字數')
else:
    print('[X] 檢查 Homework.txt 檔案字數是否符合 Hello World 字數')




